SELECT T_OPT_INFO.OPTION_NAME
FROM option_infors AS T_OPT_INFO 
	INNER join `options`  AS T_OPTS
    ON T_OPT_INFO.OPTION_INFOR_ID = T_OPTS.OPTION_INFOR_ID
	AND T_OPTS.CAR_INFOR_ID = 'CI001' ;

SELECT COUNT(*)
FROM options AS T_OPTS
WHERE T_OPTS.CAR_INFOR_ID = 'CI001';