SELECT T_FAC.COMPANY,  T_CAR_INFOR.CAR_NAME, count(*) as CNT
FROM (factorys as T_FAC
	inner join car_infors as T_CAR_INFOR
    on T_FAC.COMPANY_ID = T_CAR_INFOR.COMPANY_ID)
    inner join `options` as T_OPTS
    on T_CAR_INFOR.CAR_INFOR_ID = T_OPTS.CAR_INFOR_ID
group by  T_FAC.COMPANY_ID,  T_CAR_INFOR.CAR_INFOR_ID;
    
INSERT INTO `OPTIONS`
(OPTION_ID, CAR_INFOR_ID, OPTION_INFOR_ID)
value
('O006', 'CI001', 'OI005');

INSERT INTO `OPTIONS`
(OPTION_ID, CAR_INFOR_ID, OPTION_INFOR_ID)
value
('O007', 'CI002', 'OI004') ;

INSERT INTO `OPTIONS`
(OPTION_ID, CAR_INFOR_ID, OPTION_INFOR_ID)
value
('O008', 'CI001', 'OI003') ;

DELETE FROM `OPTIONS`
WHERE CAR_INFOR_ID = 'CI003' AND OPTION_INFOR_ID = 'CI003'
;
select * from options;

SELECT T_FAC.COMPANY,  T_CAR_INFOR.CAR_NAME
	, T_CAR_INFOR.CAR_INFOR_ID
FROM (factorys as T_FAC
	inner join car_infors as T_CAR_INFOR
    on T_FAC.COMPANY_ID = T_CAR_INFOR.COMPANY_ID) 
;

SELECT OPTION_INFOR_ID, OPTION_NAME
FROM option_infors
;
    