
CREATE TABLE ADDRESS_CODE
(
  ADDRESS         VARCHAR(50) NOT NULL COMMENT '주소',
  ADDRESS_CODE_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (ADDRESS_CODE_ID)
) COMMENT '주소코드';

CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_CODE VARCHAR(50) NOT NULL,
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별코드';

CREATE TABLE HOBBY_CORE
(
  HOBBY         VARCHAR(50) NOT NULL COMMENT '취미명',
  HOBBY_CORE_ID VARCHAR(50) NOT NULL COMMENT '유니크ID',
  PRIMARY KEY (HOBBY_CORE_ID)
) COMMENT '취미코드';

CREATE TABLE MEM_HOBBY
(
  MEMBERS_ID    VARCHAR(50) NOT NULL COMMENT '유니크ID',
  HOBBY_CORE_ID VARCHAR(50) NOT NULL COMMENT '유니크ID'
) COMMENT '회원_취미';

CREATE TABLE MEM_INFO
(
  NAME            VARCHAR(50) NOT NULL COMMENT '이름',
  AGE             INTEGER     NOT NULL COMMENT '나이',
  ADDRESS         VARCHAR(50) NOT NULL COMMENT '주소',
  PHONE_NUM       VARCHAR(50) NOT NULL COMMENT '전화번호',
  MEMBERS_ID      VARCHAR(50) NOT NULL COMMENT '유니크ID',
  GENDER_CODE     VARCHAR(50) NOT NULL,
  ADDRESS_CODE_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (MEMBERS_ID)
) COMMENT '회원정보';

CREATE TABLE MEM_LOGIN
(
  EMAIL        VARCHAR(50) NOT NULL COMMENT '이메일',
  MEM_LOGIN_ID VARCHAR(50) NOT NULL COMMENT '회원로그인ID',
  MEMBERS_ID   VARCHAR(50) NOT NULL COMMENT '유니크ID',
  PRIMARY KEY (MEM_LOGIN_ID)
) COMMENT '회원정보_로그인';

ALTER TABLE MEM_HOBBY
  ADD CONSTRAINT FK_MEM_INFO_TO_MEM_HOBBY
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEM_INFO (MEMBERS_ID);

ALTER TABLE MEM_LOGIN
  ADD CONSTRAINT FK_MEM_INFO_TO_MEM_LOGIN
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEM_INFO (MEMBERS_ID);

ALTER TABLE MEM_HOBBY
  ADD CONSTRAINT FK_HOBBY_CORE_TO_MEM_HOBBY
    FOREIGN KEY (HOBBY_CORE_ID)
    REFERENCES HOBBY_CORE (HOBBY_CORE_ID);

ALTER TABLE MEM_INFO
  ADD CONSTRAINT FK_GENDER_CODE_TO_MEM_INFO
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE MEM_INFO
  ADD CONSTRAINT FK_ADDRESS_CODE_TO_MEM_INFO
    FOREIGN KEY (ADDRESS_CODE_ID)
    REFERENCES ADDRESS_CODE (ADDRESS_CODE_ID);
