
CREATE TABLE GENDER_CODE
(
  GENDER         VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_CODE_ID VARCHAR(50) NOT NULL COMMENT '성별코드아이디',
  PRIMARY KEY (GENDER_CODE_ID)
) COMMENT '성별코드';

CREATE TABLE MEDICALCHECKUP
(
  NAME           VARCHAR(50) NULL     COMMENT '이름',
  GENDER         VARCHAR(50) NULL     COMMENT '성별',
  AGE            INTEGER     NULL     COMMENT '나이',
  HEIGHT         INTEGER     NULL     COMMENT '키',
  WEIGHT         INTEGER     NULL     COMMENT '몸무게',
  BLOOD_PRESSION INTEGER     NULL     COMMENT '혈압',
  BLOOD_SUGER    INTEGER     NULL     COMMENT '혈당',
  RESULT         VARCHAR(50) NULL     COMMENT '검진결과',
  RECHECK_LIST   VARCHAR(50) NULL     COMMENT '재검진 항목',
  KEEPING_HEALTH VARCHAR(50) NULL     COMMENT '유지방안',
  UNIQUE_ID      VARCHAR(50) NOT NULL COMMENT '유니크ID',
  GENDER_CODE_ID VARCHAR(50) NOT NULL COMMENT '성별코드아이디',
  RESULT_CODE_ID VARCHAR(50) NOT NULL COMMENT '검진결과코드아이디',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '의학검사';

CREATE TABLE RECHECK_LIST
(
  RECHECK_LIST    VARCHAR(50) NULL     COMMENT '재검진항목',
  RECHECK_LIST_ID VARCHAR(50) NOT NULL COMMENT '재검진항목ID',
  PRIMARY KEY (RECHECK_LIST_ID)
) COMMENT '재검진항목';

CREATE TABLE RECHECK_LIST_CODE
(
  UNIQUE_ID            VARCHAR(50) NOT NULL COMMENT '유니크ID',
  RECHECK_LIST_ID      VARCHAR(50) NOT NULL COMMENT '재검진항목ID',
  RECHECK_LIST_CODE_ID VARCHAR(50) NOT NULL COMMENT '재검진항목코드ID',
  PRIMARY KEY (RECHECK_LIST_CODE_ID)
) COMMENT '재검진항목코드';

CREATE TABLE RESULT_CODE
(
  RESULT         VARCHAR(50) NOT NULL COMMENT '검진결과',
  RESULT_CODE_ID VARCHAR(50) NOT NULL COMMENT '검진결과코드아이디',
  PRIMARY KEY (RESULT_CODE_ID)
) COMMENT '검진결과코드';

ALTER TABLE RECHECK_LIST_CODE
  ADD CONSTRAINT FK_MEDICALCHECKUP_TO_RECHECK_LIST_CODE
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MEDICALCHECKUP (UNIQUE_ID);

ALTER TABLE RECHECK_LIST_CODE
  ADD CONSTRAINT FK_RECHECK_LIST_TO_RECHECK_LIST_CODE
    FOREIGN KEY (RECHECK_LIST_ID)
    REFERENCES RECHECK_LIST (RECHECK_LIST_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_GENDER_CODE_TO_MEDICALCHECKUP
    FOREIGN KEY (GENDER_CODE_ID)
    REFERENCES GENDER_CODE (GENDER_CODE_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_RESULT_CODE_TO_MEDICALCHECKUP
    FOREIGN KEY (RESULT_CODE_ID)
    REFERENCES RESULT_CODE (RESULT_CODE_ID);
